package top.keng.anime.model;

import java.io.Serializable;
import java.util.Date;

public class Anime implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anime.number
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    private Short number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anime.name
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anime.j_name
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    private String jName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anime.s_day
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    private String sDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anime.ym
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    private String ym;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anime.p1
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    private String p1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anime.p2
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    private String p2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anime.brief
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    private String brief;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anime.insert_time
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    private Date insertTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anime.insert_user
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    private Long insertUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anime.update_time
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anime.update_user
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    private Long updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table anime
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anime.number
     *
     * @return the value of anime.number
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Short getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anime
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Anime withNumber(Short number) {
        this.setNumber(number);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anime.number
     *
     * @param number the value for anime.number
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public void setNumber(Short number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anime.name
     *
     * @return the value of anime.name
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anime
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Anime withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anime.name
     *
     * @param name the value for anime.name
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anime.j_name
     *
     * @return the value of anime.j_name
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public String getjName() {
        return jName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anime
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Anime withjName(String jName) {
        this.setjName(jName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anime.j_name
     *
     * @param jName the value for anime.j_name
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public void setjName(String jName) {
        this.jName = jName == null ? null : jName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anime.s_day
     *
     * @return the value of anime.s_day
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public String getsDay() {
        return sDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anime
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Anime withsDay(String sDay) {
        this.setsDay(sDay);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anime.s_day
     *
     * @param sDay the value for anime.s_day
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public void setsDay(String sDay) {
        this.sDay = sDay == null ? null : sDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anime.ym
     *
     * @return the value of anime.ym
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public String getYm() {
        return ym;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anime
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Anime withYm(String ym) {
        this.setYm(ym);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anime.ym
     *
     * @param ym the value for anime.ym
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public void setYm(String ym) {
        this.ym = ym == null ? null : ym.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anime.p1
     *
     * @return the value of anime.p1
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public String getP1() {
        return p1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anime
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Anime withP1(String p1) {
        this.setP1(p1);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anime.p1
     *
     * @param p1 the value for anime.p1
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public void setP1(String p1) {
        this.p1 = p1 == null ? null : p1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anime.p2
     *
     * @return the value of anime.p2
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public String getP2() {
        return p2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anime
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Anime withP2(String p2) {
        this.setP2(p2);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anime.p2
     *
     * @param p2 the value for anime.p2
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public void setP2(String p2) {
        this.p2 = p2 == null ? null : p2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anime.brief
     *
     * @return the value of anime.brief
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public String getBrief() {
        return brief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anime
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Anime withBrief(String brief) {
        this.setBrief(brief);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anime.brief
     *
     * @param brief the value for anime.brief
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public void setBrief(String brief) {
        this.brief = brief == null ? null : brief.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anime.insert_time
     *
     * @return the value of anime.insert_time
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anime
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Anime withInsertTime(Date insertTime) {
        this.setInsertTime(insertTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anime.insert_time
     *
     * @param insertTime the value for anime.insert_time
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anime.insert_user
     *
     * @return the value of anime.insert_user
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Long getInsertUser() {
        return insertUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anime
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Anime withInsertUser(Long insertUser) {
        this.setInsertUser(insertUser);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anime.insert_user
     *
     * @param insertUser the value for anime.insert_user
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public void setInsertUser(Long insertUser) {
        this.insertUser = insertUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anime.update_time
     *
     * @return the value of anime.update_time
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anime
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Anime withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anime.update_time
     *
     * @param updateTime the value for anime.update_time
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anime.update_user
     *
     * @return the value of anime.update_user
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anime
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Anime withUpdateUser(Long updateUser) {
        this.setUpdateUser(updateUser);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anime.update_user
     *
     * @param updateUser the value for anime.update_user
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anime
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", number=").append(number);
        sb.append(", name=").append(name);
        sb.append(", jName=").append(jName);
        sb.append(", sDay=").append(sDay);
        sb.append(", ym=").append(ym);
        sb.append(", p1=").append(p1);
        sb.append(", p2=").append(p2);
        sb.append(", brief=").append(brief);
        sb.append(", insertTime=").append(insertTime);
        sb.append(", insertUser=").append(insertUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append("]");
        return sb.toString();
    }
}