package top.keng.anime.model;

import java.io.Serializable;
import java.util.Date;

public class Carousel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.carousel_id
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    private Byte carouselId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.carousel_url
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    private String carouselUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.redirect_url
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    private String redirectUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.is_deleted
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    private String isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.insert_time
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    private Date insertTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.insert_user
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    private Long insertUser;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table carousel
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.carousel_id
     *
     * @return the value of carousel.carousel_id
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Byte getCarouselId() {
        return carouselId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Carousel withCarouselId(Byte carouselId) {
        this.setCarouselId(carouselId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.carousel_id
     *
     * @param carouselId the value for carousel.carousel_id
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public void setCarouselId(Byte carouselId) {
        this.carouselId = carouselId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.carousel_url
     *
     * @return the value of carousel.carousel_url
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public String getCarouselUrl() {
        return carouselUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Carousel withCarouselUrl(String carouselUrl) {
        this.setCarouselUrl(carouselUrl);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.carousel_url
     *
     * @param carouselUrl the value for carousel.carousel_url
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public void setCarouselUrl(String carouselUrl) {
        this.carouselUrl = carouselUrl == null ? null : carouselUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.redirect_url
     *
     * @return the value of carousel.redirect_url
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public String getRedirectUrl() {
        return redirectUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Carousel withRedirectUrl(String redirectUrl) {
        this.setRedirectUrl(redirectUrl);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.redirect_url
     *
     * @param redirectUrl the value for carousel.redirect_url
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public void setRedirectUrl(String redirectUrl) {
        this.redirectUrl = redirectUrl == null ? null : redirectUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.is_deleted
     *
     * @return the value of carousel.is_deleted
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Carousel withIsDeleted(String isDeleted) {
        this.setIsDeleted(isDeleted);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.is_deleted
     *
     * @param isDeleted the value for carousel.is_deleted
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.insert_time
     *
     * @return the value of carousel.insert_time
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Carousel withInsertTime(Date insertTime) {
        this.setInsertTime(insertTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.insert_time
     *
     * @param insertTime the value for carousel.insert_time
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.insert_user
     *
     * @return the value of carousel.insert_user
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Long getInsertUser() {
        return insertUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Carousel withInsertUser(Long insertUser) {
        this.setInsertUser(insertUser);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.insert_user
     *
     * @param insertUser the value for carousel.insert_user
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public void setInsertUser(Long insertUser) {
        this.insertUser = insertUser;
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", carouselId=").append(carouselId);
        sb.append(", carouselUrl=").append(carouselUrl);
        sb.append(", redirectUrl=").append(redirectUrl);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", insertTime=").append(insertTime);
        sb.append(", insertUser=").append(insertUser);
        sb.append("]");
        return sb.toString();
    }
}