package top.keng.anime.model;

import java.io.Serializable;
import java.util.Date;

public class Links implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column links.link_name
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    private String linkName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column links.link
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    private String link;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column links.belong
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    private Short belong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column links.subtitle
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    private String subtitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column links.insert_time
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    private Date insertTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column links.insert_user
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    private Long insertUser;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table links
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column links.link_name
     *
     * @return the value of links.link_name
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public String getLinkName() {
        return linkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Links withLinkName(String linkName) {
        this.setLinkName(linkName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column links.link_name
     *
     * @param linkName the value for links.link_name
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public void setLinkName(String linkName) {
        this.linkName = linkName == null ? null : linkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column links.link
     *
     * @return the value of links.link
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Links withLink(String link) {
        this.setLink(link);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column links.link
     *
     * @param link the value for links.link
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column links.belong
     *
     * @return the value of links.belong
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Short getBelong() {
        return belong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Links withBelong(Short belong) {
        this.setBelong(belong);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column links.belong
     *
     * @param belong the value for links.belong
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public void setBelong(Short belong) {
        this.belong = belong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column links.subtitle
     *
     * @return the value of links.subtitle
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Links withSubtitle(String subtitle) {
        this.setSubtitle(subtitle);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column links.subtitle
     *
     * @param subtitle the value for links.subtitle
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle == null ? null : subtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column links.insert_time
     *
     * @return the value of links.insert_time
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Links withInsertTime(Date insertTime) {
        this.setInsertTime(insertTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column links.insert_time
     *
     * @param insertTime the value for links.insert_time
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column links.insert_user
     *
     * @return the value of links.insert_user
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Long getInsertUser() {
        return insertUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Links withInsertUser(Long insertUser) {
        this.setInsertUser(insertUser);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column links.insert_user
     *
     * @param insertUser the value for links.insert_user
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public void setInsertUser(Long insertUser) {
        this.insertUser = insertUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", linkName=").append(linkName);
        sb.append(", link=").append(link);
        sb.append(", belong=").append(belong);
        sb.append(", subtitle=").append(subtitle);
        sb.append(", insertTime=").append(insertTime);
        sb.append(", insertUser=").append(insertUser);
        sb.append("]");
        return sb.toString();
    }
}