package top.keng.anime.model;

import java.io.Serializable;
import java.util.Date;

public class Visitor implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.user_id
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.nick_name
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.login_name
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.password_md5
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    private String passwordMd5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.avatar
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.role
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.insert_time
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    private Date insertTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.update_time
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table visitor
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.user_id
     *
     * @return the value of visitor.user_id
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Visitor withUserId(Long userId) {
        this.setUserId(userId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.user_id
     *
     * @param userId the value for visitor.user_id
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.nick_name
     *
     * @return the value of visitor.nick_name
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Visitor withNickName(String nickName) {
        this.setNickName(nickName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.nick_name
     *
     * @param nickName the value for visitor.nick_name
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.login_name
     *
     * @return the value of visitor.login_name
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Visitor withLoginName(String loginName) {
        this.setLoginName(loginName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.login_name
     *
     * @param loginName the value for visitor.login_name
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.password_md5
     *
     * @return the value of visitor.password_md5
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public String getPasswordMd5() {
        return passwordMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Visitor withPasswordMd5(String passwordMd5) {
        this.setPasswordMd5(passwordMd5);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.password_md5
     *
     * @param passwordMd5 the value for visitor.password_md5
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public void setPasswordMd5(String passwordMd5) {
        this.passwordMd5 = passwordMd5 == null ? null : passwordMd5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.avatar
     *
     * @return the value of visitor.avatar
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Visitor withAvatar(String avatar) {
        this.setAvatar(avatar);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.avatar
     *
     * @param avatar the value for visitor.avatar
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.role
     *
     * @return the value of visitor.role
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Visitor withRole(String role) {
        this.setRole(role);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.role
     *
     * @param role the value for visitor.role
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.insert_time
     *
     * @return the value of visitor.insert_time
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Visitor withInsertTime(Date insertTime) {
        this.setInsertTime(insertTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.insert_time
     *
     * @param insertTime the value for visitor.insert_time
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.update_time
     *
     * @return the value of visitor.update_time
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public Visitor withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.update_time
     *
     * @param updateTime the value for visitor.update_time
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", nickName=").append(nickName);
        sb.append(", loginName=").append(loginName);
        sb.append(", passwordMd5=").append(passwordMd5);
        sb.append(", avatar=").append(avatar);
        sb.append(", role=").append(role);
        sb.append(", insertTime=").append(insertTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}