package top.keng.anime.mapper;

import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.session.RowBounds;
import top.keng.anime.model.Anime;
import top.keng.anime.model.AnimeExample;
@Mapper
public interface AnimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anime
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    long countByExample(AnimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anime
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    int deleteByExample(AnimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anime
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    @Delete({
        "delete from anime",
        "where number = #{number,jdbcType=SMALLINT}"
    })
    int deleteByPrimaryKey(Short number);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anime
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    @Insert({
        "insert into anime (number, name, ",
        "j_name, s_day, ym, ",
        "p1, p2, brief, ",
        "insert_user, ",
        "update_user)",
        "values (#{number,jdbcType=SMALLINT}, #{name,jdbcType=VARCHAR}, ",
        "#{jName,jdbcType=VARCHAR}, #{sDay,jdbcType=CHAR}, #{ym,jdbcType=CHAR}, ",
        "#{p1,jdbcType=VARCHAR}, #{p2,jdbcType=VARCHAR}, #{brief,jdbcType=VARCHAR}, ",
        "#{insertUser,jdbcType=BIGINT}, ",
        "#{updateUser,jdbcType=BIGINT})"
    })
    int insert(Anime row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anime
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    @Insert({
            "insert into anime (number, name, ",
            "j_name, s_day, ym, ",
            "p1, p2, brief, ",
            "insert_user, ",
            "update_user)",
            "values (#{number,jdbcType=SMALLINT}, #{name,jdbcType=VARCHAR}, ",
            "#{jName,jdbcType=VARCHAR}, #{sDay,jdbcType=CHAR}, #{ym,jdbcType=CHAR}, ",
            "#{p1,jdbcType=VARCHAR}, #{p2,jdbcType=VARCHAR}, #{brief,jdbcType=VARCHAR}, ",
            " #{insertUser,jdbcType=BIGINT}, ",
            " #{updateUser,jdbcType=BIGINT})"
    })
    int insertSelective(Anime row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anime
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    List<Anime> selectByExampleWithRowbounds(AnimeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anime
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    List<Anime> selectByExample(AnimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anime
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    @Select({
        "select",
        "number, name, j_name, s_day, ym, p1, p2, brief, insert_time, insert_user, update_time, ",
        "update_user",
        "from anime",
        "where number = #{number,jdbcType=SMALLINT}"
    })
//    @ResultMap("top.keng.anime.mapper.AnimeMapper.BaseResultMap")
    Anime selectByPrimaryKey(Short number);

    @Select({
            "select * from anime;"
    })
    List<Anime> selectAllAnime();

    @Select({
            "select * from anime where concat(name,jname) like '%#{query,jdbcType=VARCHAR}%'"
    })
    List<Anime> selectByName(String query);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anime
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    int updateByExampleSelective(@Param("row") Anime row, @Param("example") AnimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anime
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    int updateByExample(@Param("row") Anime row, @Param("example") AnimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anime
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    @Update({
            "update anime",
            "set name = #{name,jdbcType=VARCHAR},",
            "j_name = #{jName,jdbcType=VARCHAR},",
            "s_day = #{sDay,jdbcType=CHAR},",
            "ym = #{ym,jdbcType=CHAR},",
            "p1 = #{p1,jdbcType=VARCHAR},",
            "p2 = #{p2,jdbcType=VARCHAR},",
            "brief = #{brief,jdbcType=VARCHAR},",
            "update_user = #{updateUser,jdbcType=BIGINT}",
            "where number = #{number,jdbcType=SMALLINT}"
    })
    int updateByPrimaryKeySelective(Anime row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anime
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    @Update({
        "update anime",
        "set name = #{name,jdbcType=VARCHAR},",
          "j_name = #{jName,jdbcType=VARCHAR},",
          "s_day = #{sDay,jdbcType=CHAR},",
          "ym = #{ym,jdbcType=CHAR},",
          "p1 = #{p1,jdbcType=VARCHAR},",
          "p2 = #{p2,jdbcType=VARCHAR},",
          "brief = #{brief,jdbcType=VARCHAR},",
          "update_user = #{updateUser,jdbcType=BIGINT}",
        "where number = #{number,jdbcType=SMALLINT}"
    })
    int updateByPrimaryKey(Anime row);
}