package top.keng.anime.mapper;

import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.session.RowBounds;
import top.keng.anime.model.Carousel;
import top.keng.anime.model.CarouselExample;
@Mapper
public interface CarouselMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    long countByExample(CarouselExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    int deleteByExample(CarouselExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    @Delete({
        "delete from carousel",
        "where carousel_id = #{carouselId,jdbcType=TINYINT}"
    })
    int deleteByPrimaryKey(Byte carouselId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    @Insert({
        "insert into carousel (carousel_id, carousel_url, ",
        "redirect_url, is_deleted, ",
        "insert_user)",
        "values (#{carouselId,jdbcType=TINYINT}, #{carouselUrl,jdbcType=VARCHAR}, ",
        "#{redirectUrl,jdbcType=VARCHAR}, #{isDeleted,jdbcType=CHAR}, ",
        "#{insertUser,jdbcType=BIGINT})"
    })
    int insert(Carousel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    @Insert({
            "insert into carousel (carousel_id, carousel_url, ",
            "redirect_url, is_deleted, ",
            "insert_user)",
            "values (#{carouselId,jdbcType=TINYINT}, #{carouselUrl,jdbcType=VARCHAR}, ",
            "#{redirectUrl,jdbcType=VARCHAR}, #{isDeleted,jdbcType=CHAR}, ",
            " #{insertUser,jdbcType=BIGINT})"
    })
    int insertSelective(Carousel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     *
     *
     */
    @Select({
            "select * from carousel"
    })
    List<Carousel> selectAll();
    List<Carousel> selectByExampleWithRowbounds(CarouselExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    List<Carousel> selectByExample(CarouselExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    @Select({
        "select",
        "carousel_id, carousel_url, redirect_url, is_deleted, insert_time, insert_user ",
        "from carousel",
        "where carousel_id = #{carouselId,jdbcType=TINYINT}"
    })
//    @ResultMap("top.keng.anime.mapper.CarouselMapper.BaseResultMap")
    Carousel selectByPrimaryKey(Byte carouselId);


}