package top.keng.anime.mapper;

import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.session.RowBounds;
import top.keng.anime.model.Links;
import top.keng.anime.model.LinksExample;
@Mapper
public interface LinksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    long countByExample(LinksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    int deleteByExample(LinksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    @Delete({
        "delete from links",
        "where link_name = #{linkName,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String linkName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    @Insert({
        "insert into links (link_name, link, ",
        "belong, subtitle, ",
        "insert_user)",
        "values (#{linkName,jdbcType=VARCHAR}, #{link,jdbcType=VARCHAR}, ",
        "#{belong,jdbcType=SMALLINT}, #{subtitle,jdbcType=VARCHAR}, ",
        "#{insertUser,jdbcType=BIGINT})"
    })
    int insert(Links row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    @Insert({
            "insert into links (link_name, link, ",
            "belong, subtitle, ",
            "insert_user)",
            "values (#{linkName,jdbcType=VARCHAR}, #{link,jdbcType=VARCHAR}, ",
            "#{belong,jdbcType=SMALLINT}, #{subtitle,jdbcType=VARCHAR}, ",
            "#{insertUser,jdbcType=BIGINT})",

    })
    int insertSelective(Links row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    List<Links> selectByExampleWithRowbounds(LinksExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    List<Links> selectByExample(LinksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    @Select({
        "select",
        "link_name, link, belong, subtitle, insert_time, insert_user, update_time, update_user",
        "from links",
        "where link_name = #{linkName,jdbcType=VARCHAR}"
    })
//    @ResultMap("top.keng.anime.mapper.LinksMapper.BaseResultMap")
    Links selectByPrimaryKey(String linkName);

    @Select({
            "select * from links where belong = #{animeNumber,jdbcType=SMALLINT}"
    })
    List<Links> selectByAnime(short animeNumber);

    @Select({
            "select * from links order by insert_time desc"
    })
    List<Links> selectAll();


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    int updateByExampleSelective(@Param("row") Links row, @Param("example") LinksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    int updateByExample(@Param("row") Links row, @Param("example") LinksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
//    int updateByPrimaryKeySelective(Links row);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table links
//     *
//     * @mbg.generated Fri May 19 10:36:22 CST 2023
//     */
//    @Update({
//        "update links",
//        "set link = #{link,jdbcType=VARCHAR},",
//          "belong = #{belong,jdbcType=SMALLINT},",
//          "subtitle = #{subtitle,jdbcType=VARCHAR},",
//          "insert_user = #{insertUser,jdbcType=BIGINT},",
//          "update_user = #{updateUser,jdbcType=BIGINT}",
//        "where link_name = #{linkName,jdbcType=VARCHAR}"
//    })
//    int updateByPrimaryKey(Links row);
}