package top.keng.anime.mapper;

import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.session.RowBounds;
import top.keng.anime.model.UserToken;
import top.keng.anime.model.UserTokenExample;

@Mapper
public interface UserTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    long countByExample(UserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    int deleteByExample(UserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    @Delete({
        "delete from user_token",
        "where user_id = #{userId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    @Insert({
        "insert into user_token (user_id, token, ",
        "insert_time, expire_time)",
        "values (#{userId,jdbcType=BIGINT}, #{token,jdbcType=VARCHAR}, ",
        "#{insertTime,jdbcType=TIMESTAMP}, #{expireTime,jdbcType=TIMESTAMP})"
    })
    int insert(UserToken row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    @Insert({
            "insert into user_token (user_id, token, ",
            "insert_time, expire_time)",
            "values (#{userId,jdbcType=BIGINT}, #{token,jdbcType=VARCHAR}, ",
            "#{insertTime,jdbcType=TIMESTAMP}, #{expireTime,jdbcType=TIMESTAMP})"
    })
    int insertSelective(UserToken row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    List<UserToken> selectByExampleWithRowbounds(UserTokenExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    List<UserToken> selectByExample(UserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    @Select({
        "select",
        "user_id, token, insert_time, expire_time",
        "from user_token",
        "where user_id = #{userId,jdbcType=BIGINT}"
    })
//    @ResultMap("top.keng.anime.mapper.UserTokenMapper.BaseResultMap")
    UserToken selectByPrimaryKey(Long userId);

    @Select({
            "select *",
            "from user_token",
            "where token = #{token,jdbcType=BIGINT}"
    })
    UserToken selectByToken(String token);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    int updateByExampleSelective(@Param("row") UserToken row, @Param("example") UserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    int updateByExample(@Param("row") UserToken row, @Param("example") UserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    @Update({
            "update user_token",
            "set token = #{token,jdbcType=VARCHAR},",
            "insert_time = #{insertTime,jdbcType=TIMESTAMP},",
            "expire_time = #{expireTime,jdbcType=TIMESTAMP}",
            "where user_id = #{userId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKeySelective(UserToken row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    @Update({
        "update user_token",
        "set token = #{token,jdbcType=VARCHAR},",
          "insert_time = #{insertTime,jdbcType=TIMESTAMP},",
          "expire_time = #{expireTime,jdbcType=TIMESTAMP}",
        "where user_id = #{userId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(UserToken row);
}