package top.keng.anime.mapper;

import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.session.RowBounds;
import top.keng.anime.model.Visitor;
import top.keng.anime.model.VisitorExample;

@Mapper
public interface VisitorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    long countByExample(VisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    int deleteByExample(VisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    @Delete({
        "delete from visitor",
        "where user_id = #{userId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    @Insert({
        "insert into visitor (nick_name, ",
        "login_name, password_md5) ",
        "values ( #{nickName,jdbcType=VARCHAR}, ",
        "#{loginName,jdbcType=VARCHAR}, #{passwordMd5,jdbcType=VARCHAR}) "
    })
    int insert(Visitor row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    @Insert({
            "insert into visitor (nick_name, ",
            "login_name, password_md5) ",
            "values (#{nickName,jdbcType=VARCHAR}, ",
            "#{loginName,jdbcType=VARCHAR}, #{passwordMd5,jdbcType=VARCHAR}) "
    })
    int insertSelective(Visitor row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    List<Visitor> selectByExampleWithRowbounds(VisitorExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    List<Visitor> selectByExample(VisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    @Select({
        "select",
        "user_id, nick_name, login_name, password_md5, avatar, role, insert_time, update_time",
        "from visitor",
        "where user_id = #{userId,jdbcType=BIGINT}"
    })
//    @ResultMap("top.keng.anime.mapper.VisitorMapper.BaseResultMap")
    Visitor selectByPrimaryKey(Long userId);

    // ~~~~~~~~~~~~~~

    @Select({
            "select *",
            "from visitor",
            "where login_name = #{loginName,jdbcType=VARCHAR}"
    })
//    @ResultMap("top.keng.anime.mapper.VisitorMapper.BaseResultMap")
    Visitor selectByLoginName(@Param("loginName") String loginName);
    // ~~~~~~~~~~~~~~
    @Select({
            "select *",
            "from visitor",
            "order by insert_time desc"
//            "limit #{start},#{limit}"
    })
//    @ResultMap("top.keng.anime.mapper.VisitorMapper.BaseResultMap")
    List<Visitor> findVisitorList();

    @Select({
            "select count(*)",
            "from visitor",
            "where 1=1"
    })
    int getTotalVisitors();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    int updateByExampleSelective(@Param("row") Visitor row, @Param("example") VisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    int updateByExample(@Param("row") Visitor row, @Param("example") VisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    @Update({
            "update visitor",
            "set nick_name = #{nickName,jdbcType=VARCHAR},",
            "login_name = #{loginName,jdbcType=VARCHAR},",
            "avatar = #{avatar,jdbcType=VARCHAR},",
            "password_md5 = #{passwordMd5,jdbcType=VARCHAR},",
            "role = #{role,jdbcType=CHAR}",
            "where user_id = #{userId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKeySelective(Visitor row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Fri May 19 10:36:22 CST 2023
     */
    @Update({
        "update visitor",
        "set nick_name = #{nickName,jdbcType=VARCHAR},",
          "login_name = #{loginName,jdbcType=VARCHAR},",
          "password_md5 = #{passwordMd5,jdbcType=VARCHAR},",
          "role = #{role,jdbcType=CHAR}",
        "where user_id = #{userId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Visitor row);


}